# Generated by Django 4.2 on 2024-12-18 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='courses.course')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='courses.course')),
                ('recorder', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_prerequisites',
                'unique_together': {('course', 'prerequisite')},
            },
        ),
    ]
