# Generated by Django 4.2 on 2024-12-23 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permissiongroups', '0001_initial'),
        ('users', '0002_loginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='permissiongroups.permissiongroup'),
        ),
    ]
