# Generated by Django 4.2 on 2024-12-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_permission_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ass',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
