# Generated by Django 4.2 on 2024-12-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='holiday_date',
            field=models.DateField(unique=True),
        ),
    ]
