# Generated by Django 4.2 on 2024-12-26 16:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentationsessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rollcalls', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rollcall',
            unique_together={('student', 'presentation_session')},
        ),
    ]
