# Generated by Django 4.2 on 2024-12-18 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessongroups', '0001_initial'),
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='lesson_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='lessongroups.lessongroup'),
        ),
    ]
