# Generated by Django 4.2 on 2024-12-21 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financialcategories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presentations', '0001_initial'),
        ('selectedexams', '0001_initial'),
        ('paycategories', '0001_initial'),
        ('selectedpresentations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('pay_reference', models.CharField(max_length=30, null=True)),
                ('record_date', models.DateField()),
                ('financial_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='financialcategories.financialcategory')),
                ('pay_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='paycategories.paycategory')),
                ('presentation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='presentations.presentation')),
                ('recorder', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('selected_exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='selectedexams.selectedexam')),
                ('selected_presentation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='selectedpresentations.selectedpresentation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'financial_transaction',
            },
        ),
    ]
