# Generated by Django 4.2 on 2024-12-20 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examschedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_participated', models.BooleanField(default=True)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('record_date', models.DateField()),
                ('exam_schedule', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='examschedules.examschedule')),
                ('recorder', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'selected_exams',
            },
        ),
    ]
