# Generated by Django 4.2 on 2024-12-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
