# Generated by Django 4.2 on 2024-12-22 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permissiongroups', '0001_initial'),
        ('permissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionGroupDefine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='permissions.permission')),
                ('permission_group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='permissiongroups.permissiongroup')),
                ('recorder', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'permission_group_defines',
            },
        ),
    ]
